### PR TITLE
improve 5.3 docker setup

### PR DESCRIPTION
**Pull request by tomerd**
motivation: pin to 5.3 nighties 

changes: use swiftlang/swift:nightly-5.3-master-bionic instead of swiftlang/swift:nightly-master-bionic

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
5.3 failed due to known NIO issue, ignoring that.

**Comment by tomerd** [comment]
hmm this test seem have been hung on both 5.0 and 5.2, not sure if a known issue?

`00:03:39.743 Test Case 'NIOSSLIntegrationTest.testNewCallbackCanDelayHandshake' started at 2020-05-05 06:09:31.372`

**Comment by Lukasa** [comment]
Build timeouts on the rest, probably congestion on the builder.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Yup, known issue, filed as #197.

**Pull request merged**
