### PR TITLE
link swift-nio-extras in docs

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
needs a PR like apple/swift-nio-extras#86

**Comment by Lukasa** [comment]
All three builds timed out during the build process.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
```
14:25:57 Running test suite 'tests_02_allocation_counters'
14:25:57 Running test 'test_01_allocation_counts.sh'... Build timed out (after 20 minutes). Marking the build as failed.
14:31:03 $ ssh-agent -k
```

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Pull request merged**
