### PR TITLE
run integration tests in CI

### LINKED ISSUE #113: Add CI support for running integration tests.

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

Integration tests are great but only if also run in CI.

Modification:

Run 'em in CI.

Result:

- fixes #113

### CODE REVIEW

**Comment by Lukasa** [comment]
Hrm, looks like `expect` is missing.

**Comment by weissi** [comment]
> Hrm, looks like `expect` is missing.

Thanks, fixed

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
```
13:51:13 ++ cat
13:51:13 ++ openssl req -new -newkey rsa:4096 -days 365 -nodes -config /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/openssl.cnf -x509 -subj /C=US/ST=NJ/L=Wall/O=NIO/CN=localhost -keyout /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem -out /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem
13:51:13 Generating a RSA private key
13:51:13 .................................................................................................++++
13:51:13 ..................................................................................++++
13:51:13 writing new private key to '/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem'
13:51:13 -----
13:51:13 +++ client_path
13:51:13 ++++ swift build --show-bin-path
13:51:13 +++ echo /code/.build/x86_64-unknown-linux/debug/NIOSSLHTTP1Client
13:51:13 ++ expect -c '
13:51:13           spawn openssl s_server -cert "/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem" -key "/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem"
13:51:13           set serverspawn $spawn_id
13:51:13           expect {
13:51:13               "ACCEPT" {
13:51:13               }
13:51:13               timeout {
13:51:13                   exit 1
13:51:13               }
13:51:13           }
13:51:13 
13:51:13           spawn /code/.build/x86_64-unknown-linux/debug/NIOSSLHTTP1Client http://localhost:4433/get "/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem" "/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem" "/tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem"
13:51:13           set spawn_id $serverspawn
13:51:13 
13:51:13           expect {
13:51:13               "close\r\r" {
13:51:13               }
13:51:13               timeout {
13:51:13                   exit 2
13:51:13               }
13:51:13           }
13:51:13           send  "R\r"
13:51:13           expect {
13:51:13               "Read BLOCK\r" {
13:51:13               }
13:51:13               timeout {
13:51:13                   exit 3
13:51:13               }
13:51:13           }
13:51:13           '
13:51:13 spawn openssl s_server -cert /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem -key /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem
13:51:13 Using default temp DH parameters
13:51:13 ACCEPT
13:51:13 spawn /code/.build/x86_64-unknown-linux/debug/NIOSSLHTTP1Client http://localhost:4433/get /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/key.pem /tmp/.swift-nio-http1-server-sh-tests_abGdCW/test.tmp_gh3rjy/cert.pem
13:51:13 -----BEGIN SSL SESSION PARAMETERS-----
13:51:13 MG4CAQECAgMEBAITAQQgafpzCK2mgyAqou1pTPI7Ogf3hz0DgUY+iiB36jSz1fcE
13:51:13 IGUg4f8W6xzhmKWbrOhJc9TpvjLW7w1GhR9teMcBzJwloQYCBF0Uu7eiBAICHCCk
13:51:13 BgQEAQAAAK4HAgUAmDEONg==
13:51:13 -----END SSL SESSION PARAMETERS-----
13:51:13 Shared ciphers:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA
13:51:13 Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
13:51:13 Shared Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
13:51:13 Supported Elliptic Groups: X25519:P-256:P-384
13:51:13 Shared Elliptic groups: X25519:P-256:P-384
13:51:13 ---
13:51:13 No server certificate CA names sent
13:51:13 CIPHER is TLS_AES_128_GCM_SHA256
13:51:13 Secure Renegotiation IS NOT supported
13:51:13 GET http://localhost:4433/get HTTP/1.1

13:51:13 Host: localhost

13:51:13 User-Agent: swift-nio

13:51:13 Accept: application/json

13:51:13 Connection: close

13:51:13 

13:51:13 R
13:51:13 SSL_do_handshake -> 1
13:51:13 --- OUTPUT  END  ---
13:51:13 FAILURE (oks: 0, failures: 1)
```

**Pull request merged**
