### PR TITLE
fix msvc min max macro collisions

### LINKED ISSUE #257: MSVC build min/max macro collisions
Hi,

When I try building `swift-nio-ssl` on Windows 

```bash
swift build -Xcxx "-Xclang" -Xcxx "-std=c++14"
````

I get following errors

```bash
\git\ai-baselines\.build\checkouts\swift-nio-ssl\Sources\CNIOBoringSSL\ssl\handoff.cc:544:61: error: too few arguments provided to function-like macro invocation
    if (ticket_age_skew > std::numeric_limits<int32_t>::max() ||
                                                            ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\minwindef.h:193:9: note: macro 'max' defined here
#define max(a,b)            (((a) > (b)) ? (a) : (b))
        ^
\git\ai-baselines\.build\checkouts\swift-nio-ssl\Sources\CNIOBoringSSL\ssl\handoff.cc:544:25: error: comparison between pointer and integer ('int64_t' (aka 'long long') and 'int (*)() noexcept')
    if (ticket_age_skew > std::numeric_limits<int32_t>::max() ||
        ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\git\ai-baselines\.build\checkouts\swift-nio-ssl\Sources\CNIOBoringSSL\ssl\handoff.cc:545:61: error: too few arguments provided to function-like macro invocation
        ticket_age_skew < std::numeric_limits<int32_t>::min()) {
                                                            ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\minwindef.h:197:9: note: macro 'min' defined here
#define min(a,b)            (((a) < (b)) ? (a) : (b))
````

This can be fixed by providing parentheses around problematic macros.
To reproduce the error you can take a look at Swift installation on Windows using MSVC as instructed here https://github.com/apple/swift/blob/main/docs/WindowsBuild.md#MSVC.

### PR DESCRIPTION
**Pull request by SercanKaraoglu**
resolves #257

### CODE REVIEW

**Comment by Lukasa** [comment]
Per #257, we are not addressing Windows support in this repository at this time. Additionally, we are reluctant to patch BoringSSL directly: we'd like to see problems like this addressed upstream if at all possible.

**Comment by SercanKaraoglu** [comment]
@Lukasa I managed to compile it on windows.

**Comment by SercanKaraoglu** [comment]
However you have one small issue to fix. You are using some c++14 features but providing c++11 as cxx setting in `Package.` file which causes the error below. If you change that to `cxxLanguageStandard: .cxx14` then the error goes away. I also tried providing `-Xcxx c++14` arguement but then it treats c files as c++ as well so only way to solve it to set it as `cxxLanguageStandard: .cxx14`. Would you like me to open an issue or PR about this @Lukasa 

```bash
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:157:15: error: deduced return types are a C++14 extension
    constexpr decltype(auto) operator()(_Args&&... _Vals) { // forward function call operator
              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1036:16: error: constexpr function's return type 'void' is not a literal type
constexpr void _Adl_verify_range(const _Iter& _First, const _Sentinel& _Last) {
               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1076:22: error: deduced return types are a C++14 extension
_NODISCARD constexpr decltype(auto) _Get_unwrapped(_Iter&& _It) {
                     ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1123:22: error: deduced return types are a C++14 extension
_NODISCARD constexpr decltype(auto) _Get_unwrapped_unverified(_Iter&& _It) {
                     ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1182:22: error: deduced return types are a C++14 extension
_NODISCARD constexpr decltype(auto) _Get_unwrapped_n(_Iter&& _It, const _Diff _Off) {
                     ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1265:16: error: constexpr function's return type 'void' is not a literal type
constexpr void _Seek_wrapped(_Iter& _It, _UIter&& _UIt) {
               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1333:1: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
auto _Idl_distance(const _Iter& _First, const _Iter& _Last) {
^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1340:16: error: no viable conversion from returned value of type 'std::_Distance_unknown' to function return type 'int'
        return _Distance_unknown{};
               ^~~~~~~~~~~~~~~~~~~
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1732:11: error: deduced return types are a C++14 extension
constexpr decltype(auto) _Operator_arrow(_Iterator&& _Target, false_type) {
          ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1827:20: error: constexpr function's return type 'void' is not a literal type
    constexpr void _Verify_offset(const difference_type _Off) const {
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1840:20: error: constexpr function's return type 'void' is not a literal type
    constexpr void _Seek_to(const reverse_iterator<_Src>& _It) {
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:1849:16: error: constexpr function's return type 'void' is not a literal type
constexpr void _Verify_range(const reverse_iterator<_BidIt>& _First, const reverse_iterator<_BidIt2>& _Last) {
               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:3096:20: error: constexpr function's return type 'void' is not a literal type
    constexpr void _Seek_to(pointer _It) {
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:3468:27: error: constexpr function's return type 'void' is not a literal type
    friend constexpr void _Verify_range(const move_iterator& _First, const move_iterator<_Iter2>& _Last) {
                          ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:3475:20: error: constexpr function's return type 'void' is not a literal type
    constexpr void _Verify_offset(const difference_type _Off) const {
                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xutility:3487:20: error: constexpr function's return type 'void' is not a literal type
    constexpr void _Seek_to(const move_iterator<_Src>& _It) {
````

**Comment by Lukasa** [comment]
Yup, I'm happy for you to open a PR for updating the CXX language standard.

**Comment by SercanKaraoglu** [comment]
> Yup, I'm happy for you to open a PR for updating the CXX language standard.

okay done! https://github.com/apple/swift-nio-ssl/pull/260 please review

**Pull request closed without merging**
