### PR TITLE
Update BoringSSL to 6ba98ff60144f60aba589b4d6121689528fbae76

### PR DESCRIPTION
**Pull request by Lukasa**
No functional changes, but paving the way for a change to the vendoring script.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
tests too slow

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
I think the 5.1 builder is busted.

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
