### PR TITLE
Remove support for Swift 5.0 and 5.1

### PR DESCRIPTION
**Pull request by Davidde94**
Changes made:

- Removed CI config for 5.0 ad 5.1
- Changed 5.2 to be based on 16.04 so we have some coverage there
- Converted Package.swift to the latest syntax
- Added a description to supported Swift versions in the README

### CODE REVIEW

**Comment by Davidde94** [comment]
Hey @yim-lee you might get tired of hearing this, but could you please work your CI magic here too?

- [ ] Remove the 5.0 and 5.1 jobs
- [ ] Update the 5.2 job to use 16.04
- [ ] Update the API breakage to be based on the Swift 5.4 Ubuntu 20.04 image

**Review by Lukasa — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-nio-bot test this please

**Comment by yim-lee** [comment]
@swift-nio-bot test this please

**Comment by yim-lee** [comment]
@Davidde94 CI changes are done.

- Added 5.4 to required list
- Fixed name of 5.5 job to "pull request validation (5.5)". Please ignore swift-nio-ssl2-swift55-prb.

**Pull request merged**
