### PR TITLE
fclose takes Nonnull FILE pointer in Swift >=5.9

### LINKED ISSUE #429: Compilation fails on Linux with Swift 5.9-dev
Importation of `fclose` on Linux appears to have changed with Swift 5.9 (`Swift version 5.9-dev (LLVM 6665c55e557222b, Swift b370e7dbea9ca19)`) and `internal typealias FILEPointer = UnsafeMutablePointer<FILE>` in `NIOSSL/PosixPort.swift` fails to compile.

`/home/ryan/Projects/Develop/Tsunami/.build/checkouts/swift-nio-ssl/Sources/NIOSSL/PosixPort.swift:42:64: error: cannot convert value of type '(UnsafeMutablePointer<FILE>) -> Int32' (aka '(UnsafeMutablePointer<_IO_FILE>) -> Int32') to specified type '@convention(c) (FILEPointer?) -> CInt' (aka '@convention(c) (Optional<UnsafeMutablePointer<_IO_FILE>>) -> Int32')
private let sysFclose: @convention(c) (FILEPointer?) -> CInt = fclose`

Changing the `sysFclose` definition to `private let sysFclose: @convention(c) ((FILEPointer)?) -> CInt = fclose` by putting FILEPointer in brackets matches the expected method signature and allows compilation to succeed, but there may be a better way to solve this (or wrapping this in a Swift 5.9 conditional).

### PR DESCRIPTION
**Pull request by tokyovigilante**
Closes #429.

### CODE REVIEW

**Review by Lukasa — CHANGES_REQUESTED** [review]
Unfortunately this needs a bit of a tweak, as right now the change affects both Linux and Apple platforms, where the signature hasn't changed.

Can you use the per-OS blocks below to make this change affect only Linux?

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
Hmm, this appears to be a bit overzealous, as our CI is failing the build:

```
16:45:30 /code/Sources/NIOSSL/PosixPort.swift:44:63: error: C function pointer signature '(UnsafeMutablePointer<FILE>?) -> Int32' (aka '(Optional<UnsafeMutablePointer<_IO_FILE>>) -> Int32') is not compatible with expected type '@convention(c) (FILEPointer) -> CInt' (aka '@convention(c) (UnsafeMutablePointer<_IO_FILE>) -> Int32')
```

What Linux distribution did you test on?

**Comment by tokyovigilante** [comment]
> What Linux distribution did you test on?
Fedora rawhide, with Clang 16 and glibc 2.37.9.

**Comment by Lukasa** [comment]
This is _probably_ more that combination. We can probably get around this by redeclaring the variable as a closure wrapping the underlying function:

```swift
private let sysFclose: @convention(c) (FILEPointer?) -> CInt = { fclose($0) }
```

**Comment by Saljooq** [comment]
@Lukasa I tried your fix but the argument had to be unwrapped, this is the version that worked:
```swift
private let sysFclose: @convention(c) (FILEPointer?) -> CInt =  { fclose($0!) }
```
cc: @tokyovigilante

**Pull request closed without merging**
