### PR TITLE
@_implementationOnly also for Swift 5.3

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

@_implementationOnly also works in Swift 5.3, let's use it.

Modification:

Use @_implementationOnly for Swift 5.1 ... 5.3

Result:

Proper 5.3 support.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
hit #197

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
hit #210

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
And lo, the flaky tests have been resolved.

**Pull request merged**
