### PR TITLE
Update BoringSSL to 2fc6d38391cb76839c76b2a462619e7d69fd998d

### PR DESCRIPTION
**Pull request by Lukasa**

### CODE REVIEW

**Review by fabianfett — APPROVED** [review]
LGTM. Nice small change!

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
Superseded by #356.

**Pull request closed without merging**
