### PR TITLE
Update podspec script to remove 'S' files from watchOS target

### LINKED ISSUE #276: Remove 'S' files from watchOS target in CocoaPods
SwiftNIOSSL currently fails app store validation when rebuilding from Bitcode due to the presence of the assembly files. While it isn't currently possible to remove these files from SwiftPM-built targets, we can remove them from CocoaPods targets. As such, I believe the podspec should be updated to remove these files from watchOS and the latest version redeployed to the CocoaPods spec repo. This will enable a workaround for watchOS projects until SwiftPM adds the necessary support.

More context in #251

### PR DESCRIPTION
**Pull request by daltonclaybrook**
This PR resolves #276

### CODE REVIEW

**Comment by Lukasa** [comment]
@daltonclaybrook Should this patch also provide the #NO_ASM flag for watchOS, so we can get you all the way to “works fine” for your use-case?

**Comment by daltonclaybrook** [comment]
@Lukasa Good thinking, just added that to the podspec. Let me know if this looks correct to you. In my testing, when I use `$(inherited)` with `GCC_PREPROCESSOR_DEFINITIONS`, the Pods project ends up with two instances of that variable. Not sure why this is happening, but I omitted it.
GCC_PREPROCESSOR_DEFINITIONS

**Review by Lukasa — APPROVED** [review]
This LGTM, I think. @glbrntt want to take a look as well?

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Review by glbrntt — APPROVED** [review]
Looks good to me.

**Comment by daltonclaybrook** [comment]
Can the podspec be republished for 2.10.3, or will it have to wait for another version?

**Comment by Lukasa** [comment]
I don't believe we can publish a pod spec for the same version again. However, I'm open to cutting a new release explicitly to provide the new pod spec. @glbrntt, how do you feel here?

**Comment by glbrntt** [comment]
New release sounds fine to me.

**Pull request merged**
